# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f68317fa42e95772e4af2a2082d3e4edb7c511e2968e1cb84badee620dad6f7d2ed5dcd7aa4df24052f1ca307cd85cf26dad73476b26b931bd6b71ef63917d6

test:
  secret_key_base: ae82c4dcccc94f7fd99ea058d25c452e129123643cb4b48522a908d3f7f47dac306d987e174da0e016c7495b6e220ea1ed3e5f2d8a00da102953546258ab92e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
